version: '3'
services:
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
  
    volumes:
     - sonarqube-data:/opt/sonarqube1/data
     - sonarqube-logs:/opt/sonarqube1/logs
    - sonarqube-extensions:/opt/sonarqube1/extensions
      - ./plugins:/opt/sonarqube/extensions1/plugins

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data1

volumes:
 sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
  nexus-data:

