version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    networks:
      - mysqlnetwork
    environment:
      MYSQL_ROOT_PASSWORD: 's!fK/O50tJrap.KN'

  kaddem:
    image: khalil/khaddem:latest
    container_name: kaddem-container
    networks:
      - mysqlnetwork
    ports:
      - "8089:8089"



networks:
  mysqlnetwork:
